### PR TITLE
Feature authenticate user

### PR DESCRIPTION
**Pull request by bizip**
# What does this PR do?
>- Enable user to log in with Microsoft
>- Navigate logged in user to the dashboard
>- Add logout functionalities

# Description of Task to be completed?
>- Finalize unit test

## Requirements

- [x] Require dependencies installation
- [ ] Require .env update
- [ ] Documentation updated

# How should this be manually tested?
> - Clone this repository
> - checkout to this branch `ft-authentication`
> - install the dependencies `yearn install` and 
> - Run database migrations `npm run db:migrate 
> - Go to `http://localhost:3000` in your browser to access the login page

# Any background context you want to provide?
>- N/A
# What are the relevant pivotal tracker stories?
>- N/A
# Screenshots (if appropriate)

# Questions:
>- N/A

### CODE REVIEW

**Review by kabundege — CHANGES_REQUESTED** [review]
should add .yarn directory in gitignore

**Review by nicele08 — CHANGES_REQUESTED** [review]
I left some feedback.

**Review by nicele08 — CHANGES_REQUESTED** [review]
@bizip I can see there are some feedbacks you didn't work on, please fix them and we move forward. Apart from that you did great job.

**Review by nicele08 — APPROVED** [review]
@bizip well done

**Review by Cherubln — APPROVED** [review]
LGTM

**Review by kabundege — APPROVED** [review]

**Pull request merged**
